# email_sync.yaml
schedule:
  interval: daily  # Opzioni: hourly, daily, weekly
  time: '02:00'   # Ora di sincronizzazione

accounts:
  - source:
      host: imap.gmail.com
      username: email1@gmail.com
      password: app_password_gmail
    destination:
      host: localhost
      username: local_user1
      password: local_password
    options:
      ssl1: 1
      ssl2: 1
      delete2duplicates: 1
      folder: 'INBOX'

  - source:
      host: outlook.office365.com
      username: email2@outlook.com
      password: app_password_outlook
    destination:
      host: localhost
      username: local_user2
      password: local_password
    options:
      ssl1: 1
      ssl2: 1
      delete2duplicates: 1